//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod163.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ord
    {
        public decimal Cost { get; set; }
        public System.DateTime Data { get; set; }
        public string раб { get; set; }
        public string клиент { get; set; }
    }
}
